// Mocks generated by Mockito 5.4.2 from annotations
// in medical_device_classifier/test/features/dashboard/presentation/cubit/dashboard_cubit_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i6;

import 'package:medical_device_classifier/bootstrap.dart' as _i5;
import 'package:medical_device_classifier/content_files/content_loader.dart'
    as _i4;
import 'package:medical_device_classifier/shared_preferences/mdc_shared_preferences.dart'
    as _i3;
import 'package:medical_device_classifier/supabase/supabase_client.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeISupabaseClient_0 extends _i1.SmartFake
    implements _i2.ISupabaseClient {
  _FakeISupabaseClient_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeMDCSharedPreferences_1 extends _i1.SmartFake
    implements _i3.MDCSharedPreferences {
  _FakeMDCSharedPreferences_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeContentLoader_2 extends _i1.SmartFake implements _i4.ContentLoader {
  _FakeContentLoader_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [BootstrapImpl].
///
/// See the documentation for Mockito's code generation for more information.
class MockBootstrapImpl extends _i1.Mock implements _i5.BootstrapImpl {
  @override
  _i2.ISupabaseClient get supabaseClient => (super.noSuchMethod(
        Invocation.getter(#supabaseClient),
        returnValue: _FakeISupabaseClient_0(
          this,
          Invocation.getter(#supabaseClient),
        ),
        returnValueForMissingStub: _FakeISupabaseClient_0(
          this,
          Invocation.getter(#supabaseClient),
        ),
      ) as _i2.ISupabaseClient);

  @override
  _i3.MDCSharedPreferences get mdcSharedPreferences => (super.noSuchMethod(
        Invocation.getter(#mdcSharedPreferences),
        returnValue: _FakeMDCSharedPreferences_1(
          this,
          Invocation.getter(#mdcSharedPreferences),
        ),
        returnValueForMissingStub: _FakeMDCSharedPreferences_1(
          this,
          Invocation.getter(#mdcSharedPreferences),
        ),
      ) as _i3.MDCSharedPreferences);

  @override
  _i4.ContentLoader get contentLoaderImpl => (super.noSuchMethod(
        Invocation.getter(#contentLoaderImpl),
        returnValue: _FakeContentLoader_2(
          this,
          Invocation.getter(#contentLoaderImpl),
        ),
        returnValueForMissingStub: _FakeContentLoader_2(
          this,
          Invocation.getter(#contentLoaderImpl),
        ),
      ) as _i4.ContentLoader);

  @override
  _i6.Future<bool> boot() => (super.noSuchMethod(
        Invocation.method(
          #boot,
          [],
        ),
        returnValue: _i6.Future<bool>.value(false),
        returnValueForMissingStub: _i6.Future<bool>.value(false),
      ) as _i6.Future<bool>);
}
